name: auto-update-as

on:
  workflow_dispatch:
  schedule:
  - cron: '0 2 * * *'

jobs:
  auto-update-as:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}

    - name: Run auto-update-as
      run: |
        cron.d/update-AS-trends.sh

    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Apply auto-update-as changes
